# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('timestamp', models.FloatField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('has_notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('feed_id', models.CharField(max_length=100)),
                ('video_id', models.CharField(max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('video_title', models.CharField(default='', max_length=250)),
                ('video_thumbnail', models.CharField(default='', max_length=500)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link_format', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discover_expression', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('prompt_for_password', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Provider')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Provider'),
        ),
        migrations.AddField(
            model_name='comment',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Feed'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.Comment'),
        ),
    ]
