# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_project_deleted'),
        ('feed', '0009_comment_done'),
    ]

    operations = [
    ]
