# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_datamigration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
