# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_subscription_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='vimeo_scope',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='vimeo_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
