# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170319_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='youtube_credentials',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
