# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 22:19
from __future__ import unicode_literals

from django.db import migrations
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_subscription_youtube_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='youtube_credentials',
            field=oauth2client.contrib.django_util.models.CredentialsField(blank=True, null=True),
        ),
    ]
